{
 "title": "HashData集群监控",
 "description": "HashData集群监控",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "cluster", "query": "label_values(instance)" },
   {
    "name": "version",
    "query": "label_values(hashdata_cluster_state{instance=~\"$cluster\"}, version)"
   },
   {
    "name": "hdw_version",
    "query": "label_values(hashdata_cluster_state{instance=~\"$cluster\"}, hdw_version)"
   }
  ]
 },
 "panels": [
  {
   "title": "运行时间",
   "type": "gauge",
   "description": "HashData集群截至到当前的运行总时长",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "hashdata_cluster_uptime{instance=~\"$cluster\"}",
     "legendFormat": "运行时间"
    }
   ]
  },
  {
   "title": "HashData版本",
   "type": "text",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "content": "<font size=10><center>$hdw_version</center></font>\n",
   "targets": [
    { "expr": "hashdata_cluster_state" }
   ]
  },
  {
   "title": "内核版本",
   "type": "text",
   "description": "内核版本",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "content": "<font size=10><center>$version</center></font>\n\n\n",
   "targets": [
    { "expr": "hashdata_cluster_state" }
   ]
  },
  {
   "title": "集群数据总量",
   "type": "stat",
   "description": "hashdata数据库的总数据量",
   "gridPos": { "h": 4, "w": 2, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(hashdata_node_database_name_mb_size{instance=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "当前连接数",
   "type": "stat",
   "description": "当前连接总数",
   "gridPos": { "h": 4, "w": 2, "x": 11, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "hashdata_cluster_total_connections{instance=~\"$cluster\"}"
    }
   ]
  },
  {
   "title": "最大允许连接数",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 13, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "hashdata_cluster_max_connections{instance=~\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Master可用",
   "type": "gauge",
   "description": "hashdata集群的Master节点是否可连通",
   "gridPos": { "h": 4, "w": 2, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "hashdata_up{instance=~\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Standby同步",
   "type": "gauge",
   "description": "hashdata集群的Standby节点是否正在保持与Master的同步",
   "gridPos": { "h": 4, "w": 2, "x": 17, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "hashdata_cluster_sync{instance=~\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Segment实例在线状态",
   "type": "table",
   "description": "列举集群的Segment实例在线状态",
   "gridPos": { "h": 12, "w": 9, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "hashdata_node_segment_status{instance=~\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Segment实例同步模式",
   "type": "table",
   "description": "列举集群的Segment实例同步模式",
   "gridPos": { "h": 12, "w": 9, "x": 9, "y": 4 },
   "targets": [
    {
     "expr": "hashdata_node_segment_mode{instance=~\"$cluster\"}"
    }
   ]
  },
  {
   "title": "当前Segment剩余存储空间",
   "type": "table",
   "description": "hashdata数据存储节点的剩余可用存储空间",
   "gridPos": { "h": 12, "w": 6, "x": 18, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "expr": "hashdata_node_segment_disk_free_gb_size{instance=~\"$cluster\"}",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "各数据库内表的总数目",
   "type": "table",
   "description": "展示各数据库内表的总数目历史趋势信息",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "hashdata_node_database_table_total_count{instance=~\"$cluster\"}",
     "legendFormat": "{{dbname}}"
    }
   ]
  },
  {
   "title": "当前数据库大小",
   "type": "table",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "hashdata_node_database_name_mb_size{instance=~\"$cluster\"}"
    }
   ]
  },
  {
   "title": "膨胀垃圾数据列表",
   "type": "table",
   "description": "列举存在膨胀数据表的信息(需要数据库后端定期或定时使用analyzedb工具分析生成统计数据)",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 16 },
   "targets": [
    {
     "expr": "hashdata_server_heap_table_bloat_detail{instance=~\"$cluster\"}"
    }
   ]
  },
  {
   "title": "数据库审计日志",
   "type": "table",
   "description": "默认只显示一天之内的drop，truncate以及delete操作。",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "hashdata_server_master_log_detail"
    }
   ]
  },
  {
   "title": "倾斜表",
   "type": "table",
   "description": "只显示大于1G并且倾斜超过20%的表",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "hashdata_server_dataSkew_detail{instance=~\"$cluster\"}"
    }
   ]
  },
  {
   "title": "数据库连接数折线历史图",
   "type": "graph",
   "description": "展示各个账号的活动连接数趋势信息",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "hashdata_cluster_active_connections{instance=~\"$cluster\"}",
     "legendFormat": "活动连接数"
    },
    {
     "expr": "hashdata_cluster_total_connections{instance=~\"$cluster\"}",
     "legendFormat": "总连接数"
    }
   ]
  },
  {
   "title": "数据库进程实时列表",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "hashdata_server_activity_detail{instance=~\"$cluster\"}"
    }
   ]
  },
  {
   "title": "数据库进程内存使用实时列表",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 57 },
   "targets": [
    {
     "expr": "hashdata_server_session_memory_detail{instance=~\"$cluster\"}"
    }
   ]
  },
  {
   "title": "数据库锁状态实时列表",
   "type": "table",
   "description": "列举了当前监听的客户端访问数据库操作时的锁信息",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 64 },
   "targets": [
    {
     "expr": "hashdata_server_locks_table_detail{instance=~\"$cluster\"}"
    }
   ]
  }
 ]
}